//
// AboveAverage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describe the AboveAverage conditional formatting rule. This conditional formatting     rule highlights cells that are above or below the average for all values     in the range. */

public struct AboveAverage: Codable {

    /** Get or set the flag indicating whether the rule is an \&quot;above average\&quot; rule.    &#39;true&#39; indicates &#39;above average&#39;.  Default value is true.              */
    public var isAboveAverage: Bool
    /** Get or set the flag indicating whether the &#39;aboveAverage&#39; and &#39;belowAverage&#39;    criteria is inclusive of the average itself, or exclusive of that value.    &#39;true&#39; indicates to include the average value in the criteria.  Default value    is false.              */
    public var isEqualAverage: Bool
    /** Get or set the number of standard deviations to include above or below the   average in the conditional formatting rule. The input value must between   0 and 3 (include 0 and 3). Setting this value to 0 means stdDev is not set.    The default value is 0.              */
    public var stdDev: Int32

public enum CodingKeys: String, CodingKey { 
        case isAboveAverage = "IsAboveAverage"
        case isEqualAverage = "IsEqualAverage"
        case stdDev = "StdDev"
    }

    public init(isAboveAverage: Bool, isEqualAverage: Bool, stdDev: Int32) {
        self.isAboveAverage = isAboveAverage
        self.isEqualAverage = isEqualAverage
        self.stdDev = stdDev
    }


}

