//
// AutoFitterOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AutoFitterOptions: Codable {

    public var ignoreHidden: Bool
    public var onlyAuto: Bool
    public var autoFitMergedCells: Bool

public enum CodingKeys: String, CodingKey { 
        case ignoreHidden = "IgnoreHidden"
        case onlyAuto = "OnlyAuto"
        case autoFitMergedCells = "AutoFitMergedCells"
    }

    public init(ignoreHidden: Bool, onlyAuto: Bool, autoFitMergedCells: Bool) {
        self.ignoreHidden = ignoreHidden
        self.onlyAuto = onlyAuto
        self.autoFitMergedCells = autoFitMergedCells
    }


}

