//
// AutoShapeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AutoShapeResponse: Codable {

    public var status: String?
    public var code: Int32
    public var autoShape: AutoShape?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case autoShape = "AutoShape"
    }

    public init(status: String?, code: Int32, autoShape: AutoShape?) {
        self.status = status
        self.code = code
        self.autoShape = autoShape
    }


}

