//
// AutoFilterResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AutoFilterResponse: Codable {

    public var status: String?
    public var code: Int32
    public var autoFilter: AutoFilter?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case autoFilter = "AutoFilter"
    }

    public init(status: String?, code: Int32, autoFilter: AutoFilter?) {
        self.status = status
        self.code = code
        self.autoFilter = autoFilter
    }


}

