//
// AutoShapeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class AutoShapeResponse: CellsCloudResponse {

    public var autoShape: AutoShape?

public enum CodingKeys: String, CodingKey {
        case autoShape = "AutoShape"
    }

    public init(status: String?, code: Int32, autoShape: AutoShape?) {
        self.autoShape = autoShape
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(autoShape, forKey: "AutoShape")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        autoShape = try container.decodeIfPresent(AutoShape.self, forKey: "AutoShape")
        try super.init(from: decoder)
    }

}

