//
// AutoShapes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AutoShapes: Codable {

    public var link: Link?
    public var autoShapeList: [LinkElement]?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case autoShapeList = "AutoShapeList"
    }

    public init(link: Link?, autoShapeList: [LinkElement]?) {
        self.link = link
        self.autoShapeList = autoShapeList
    }


}

