//
// CalculationOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CalculationOptions: Codable {

    public var precisionStrategy: String?
    public var ignoreError: Bool?
    public var recursive: Bool?
    public var calcStackSize: Int32?

public enum CodingKeys: String, CodingKey { 
        case precisionStrategy = "PrecisionStrategy"
        case ignoreError = "IgnoreError"
        case recursive = "Recursive"
        case calcStackSize = "CalcStackSize"
    }

    public init(precisionStrategy: String?, ignoreError: Bool?, recursive: Bool?, calcStackSize: Int32?) {
        self.precisionStrategy = precisionStrategy
        self.ignoreError = ignoreError
        self.recursive = recursive
        self.calcStackSize = calcStackSize
    }


}

