//
// CellsDocumentProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CellsDocumentProperty: Codable {

    public var link: Link?
    public var builtIn: String?
    public var name: String?
    public var value: String?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case builtIn = "BuiltIn"
        case name = "Name"
        case value = "Value"
    }

    public init(link: Link?, builtIn: String?, name: String?, value: String?) {
        self.link = link
        self.builtIn = builtIn
        self.name = name
        self.value = value
    }


}

