//
// CellsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CellsResponse: Codable {

    public var status: String?
    public var code: Int32
    public var cells: Cells?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case cells = "Cells"
    }

    public init(status: String?, code: Int32, cells: Cells?) {
        self.status = status
        self.code = code
        self.cells = cells
    }


}

