//
// CellsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CellsResponse: CellsCloudResponse {

    public var cells: Cells?

public enum CodingKeys: String, CodingKey {
        case cells = "Cells"
    }

    public init(status: String?, code: Int32, cells: Cells?) {
        self.cells = cells
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(cells, forKey: "Cells")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        cells = try container.decodeIfPresent(Cells.self, forKey: "Cells")
        try super.init(from: decoder)
    }

}

