//
// CellsObjectOperateTaskParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CellsObjectOperateTaskParameter: Codable {

    public var operateParameter: OperateParameter?
    public var destinationWorkbook: FileSource?
    public var operateObject: OperateObject?

public enum CodingKeys: String, CodingKey { 
        case operateParameter = "OperateParameter"
        case destinationWorkbook = "DestinationWorkbook"
        case operateObject = "OperateObject"
    }

    public init(operateParameter: OperateParameter?, destinationWorkbook: FileSource?, operateObject: OperateObject?) {
        self.operateParameter = operateParameter
        self.destinationWorkbook = destinationWorkbook
        self.operateObject = operateObject
    }


}

