//
// CellResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CellResponse: CellsCloudResponse {

    public var cell: Cell?

public enum CodingKeys: String, CodingKey {
        case cell = "Cell"
    }

    public init(status: String?, code: Int32, cell: Cell?) {
        self.cell = cell
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(cell, forKey: "Cell")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        cell = try container.decodeIfPresent(Cell.self, forKey: "Cell")
        try super.init(from: decoder)
    }

}

