//
// CellsCloudFileInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CellsCloudFileInfo: Codable {

    public var name: String?
    public var size: Int64
    public var folder: String?
    public var storage: String?

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case size = "Size"
        case folder = "Folder"
        case storage = "Storage"
    }

    public init(name: String?, size: Int64, folder: String?, storage: String?) {
        self.name = name
        self.size = size
        self.folder = folder
        self.storage = storage
    }


}

