//
// ChartsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChartsResponse: Codable {

    public var status: String?
    public var code: Int32
    public var charts: Charts?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case charts = "Charts"
    }

    public init(status: String?, code: Int32, charts: Charts?) {
        self.status = status
        self.code = code
        self.charts = charts
    }


}

