//
// ChartAreaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChartAreaResponse: Codable {

    public var status: String?
    public var code: Int32
    public var chartArea: ChartArea?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case chartArea = "ChartArea"
    }

    public init(status: String?, code: Int32, chartArea: ChartArea?) {
        self.status = status
        self.code = code
        self.chartArea = chartArea
    }


}

