//
// Color.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Color: Codable {

    public var A: Int32
    public var B: Int32
    public var R: Int32
    public var G: Int32

public enum CodingKeys: String, CodingKey { 
        case A = "A"
        case B = "B"
        case R = "R"
        case G = "G"
    }

    public init(A: Int32, B: Int32, R: Int32, G: Int32) {
        self.A = A
        self.B = B
        self.R = R
        self.G = G
    }


}

