//
// ColorFilterRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ColorFilterRequest: Codable {

    public var pattern: String?
    public var foregroundColor: CellsColor?
    public var backgroundColor: CellsColor?

public enum CodingKeys: String, CodingKey { 
        case pattern = "Pattern"
        case foregroundColor = "ForegroundColor"
        case backgroundColor = "BackgroundColor"
    }

    public init(pattern: String?, foregroundColor: CellsColor?, backgroundColor: CellsColor?) {
        self.pattern = pattern
        self.foregroundColor = foregroundColor
        self.backgroundColor = backgroundColor
    }


}

