//
// ColumnResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ColumnResponse: Codable {

    public var status: String?
    public var code: Int32
    public var column: Column?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case column = "Column"
    }

    public init(status: String?, code: Int32, column: Column?) {
        self.status = status
        self.code = code
        self.column = column
    }


}

