//
// Column.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Column: Codable {

    public var link: Link?
    public var index: Int32?
    public var style: LinkElement?
    public var groupLevel: Int32?
    public var isHidden: Bool?
    public var width: Double?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case index = "Index"
        case style = "Style"
        case groupLevel = "GroupLevel"
        case isHidden = "IsHidden"
        case width = "Width"
    }

    public init(link: Link?, index: Int32?, style: LinkElement?, groupLevel: Int32?, isHidden: Bool?, width: Double?) {
        self.link = link
        self.index = index
        self.style = style
        self.groupLevel = groupLevel
        self.isHidden = isHidden
        self.width = width
    }


}

