//
// ColumnsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ColumnsResponse: CellsCloudResponse {

    public var columns: Columns?

public enum CodingKeys: String, CodingKey {
        case columns = "Columns"
    }

    public init(status: String?, code: Int32, columns: Columns?) {
        self.columns = columns
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(columns, forKey: "Columns")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        columns = try container.decodeIfPresent(Columns.self, forKey: "Columns")
        try super.init(from: decoder)
    }

}

