//
// ConvertTaskParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConvertTaskParameter: Codable {

    public var workbook: FileSource?
    public var saveOptions: SaveOptions?
    public var destinationFile: String?

public enum CodingKeys: String, CodingKey { 
        case workbook = "Workbook"
        case saveOptions = "SaveOptions"
        case destinationFile = "DestinationFile"
    }

    public init(workbook: FileSource?, saveOptions: SaveOptions?, destinationFile: String?) {
        self.workbook = workbook
        self.saveOptions = saveOptions
        self.destinationFile = destinationFile
    }


}

