//
// CustomFilter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomFilter: Codable {

    public var filterOperatorType: String?

public enum CodingKeys: String, CodingKey { 
        case filterOperatorType = "FilterOperatorType"
    }

    public init(filterOperatorType: String?) {
        self.filterOperatorType = filterOperatorType
    }


}

