//
// DataSorter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DataSorter: Codable {

    public var caseSensitive: Bool?
    public var keyList: [SortKey]?
    public var hasHeaders: Bool?
    public var sortLeftToRight: Bool?

public enum CodingKeys: String, CodingKey { 
        case caseSensitive = "CaseSensitive"
        case keyList = "KeyList"
        case hasHeaders = "HasHeaders"
        case sortLeftToRight = "SortLeftToRight"
    }

    public init(caseSensitive: Bool?, keyList: [SortKey]?, hasHeaders: Bool?, sortLeftToRight: Bool?) {
        self.caseSensitive = caseSensitive
        self.keyList = keyList
        self.hasHeaders = hasHeaders
        self.sortLeftToRight = sortLeftToRight
    }


}

