//
// ErrorDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The error details */

public struct ErrorDetails: Codable {

    /** The request id */
    public var requestId: String?
    /** Date */
    public var date: String

public enum CodingKeys: String, CodingKey { 
        case requestId = "RequestId"
        case date = "Date"
    }

    public init(requestId: String?, date: String) {
        self.requestId = requestId
        self.date = date
    }


}

