//
// FileVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** File Version */

public struct FileVersion: Codable {

    /** File or folder name. */
    public var name: String?
    /** True if it is a folder. */
    public var isFolder: Bool
    /** File or folder last modified DateTime. */
    public var modifiedDate: String?
    /** File or folder size. */
    public var size: Int64
    /** File or folder path. */
    public var path: String?
    /** File Version ID. */
    public var versionId: String?
    /** Specifies whether the file is (true) or is not (false) the latest version of an file. */
    public var isLatest: Bool

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case isFolder = "IsFolder"
        case modifiedDate = "ModifiedDate"
        case size = "Size"
        case path = "Path"
        case versionId = "VersionId"
        case isLatest = "IsLatest"
    }

    public init(name: String?, isFolder: Bool, modifiedDate: String?, size: Int64, path: String?, versionId: String?, isLatest: Bool) {
        self.name = name
        self.isFolder = isFolder
        self.modifiedDate = modifiedDate
        self.size = size
        self.path = path
        self.versionId = versionId
        self.isLatest = isLatest
    }


}

