//
// FilterColumn.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FilterColumn: Codable {

    public var filterType: String?
    public var multipleFilters: MultipleFilters?
    public var customFilters: [CustomFilter]?
    public var dynamicFilter: DynamicFilter?
    public var colorFilter: ColorFilter?
    public var fieldIndex: Int32
    public var top10Filter: Top10Filter?
    public var iconFilter: IconFilter?
    public var visibledropdown: String?

public enum CodingKeys: String, CodingKey { 
        case filterType = "FilterType"
        case multipleFilters = "MultipleFilters"
        case customFilters = "CustomFilters"
        case dynamicFilter = "DynamicFilter"
        case colorFilter = "ColorFilter"
        case fieldIndex = "FieldIndex"
        case top10Filter = "Top10Filter"
        case iconFilter = "IconFilter"
        case visibledropdown = "Visibledropdown"
    }

    public init(filterType: String?, multipleFilters: MultipleFilters?, customFilters: [CustomFilter]?, dynamicFilter: DynamicFilter?, colorFilter: ColorFilter?, fieldIndex: Int32, top10Filter: Top10Filter?, iconFilter: IconFilter?, visibledropdown: String?) {
        self.filterType = filterType
        self.multipleFilters = multipleFilters
        self.customFilters = customFilters
        self.dynamicFilter = dynamicFilter
        self.colorFilter = colorFilter
        self.fieldIndex = fieldIndex
        self.top10Filter = top10Filter
        self.iconFilter = iconFilter
        self.visibledropdown = visibledropdown
    }


}

