//
// Font.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Font: Codable {

    public var isItalic: Bool?
    public var name: String?
    public var doubleSize: Double?
    public var color: Color?
    public var isBold: Bool?
    public var isSubscript: Bool?
    public var isSuperscript: Bool?
    public var isStrikeout: Bool?
    public var underline: String?
    public var size: Int32?

public enum CodingKeys: String, CodingKey { 
        case isItalic = "IsItalic"
        case name = "Name"
        case doubleSize = "DoubleSize"
        case color = "Color"
        case isBold = "IsBold"
        case isSubscript = "IsSubscript"
        case isSuperscript = "IsSuperscript"
        case isStrikeout = "IsStrikeout"
        case underline = "Underline"
        case size = "Size"
    }

    public init(isItalic: Bool?, name: String?, doubleSize: Double?, color: Color?, isBold: Bool?, isSubscript: Bool?, isSuperscript: Bool?, isStrikeout: Bool?, underline: String?, size: Int32?) {
        self.isItalic = isItalic
        self.name = name
        self.doubleSize = doubleSize
        self.color = color
        self.isBold = isBold
        self.isSubscript = isSubscript
        self.isSuperscript = isSuperscript
        self.isStrikeout = isStrikeout
        self.underline = underline
        self.size = size
    }


}

