//
// FormatCondition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FormatCondition: Codable {

    public var link: Link?
    public var aboveAverage: AboveAverage?
    public var formula2: String?
    public var style: Style?
    public var formula1: String?
    public var colorScale: ColorScale?
    public var dataBar: DataBar?
    public var text: String?
    /** True, no rules with lower priority may be applied over this rule, when this     rule evaluates to true.  Only applies for Excel 2007; */
    public var stopIfTrue: Bool?
    /** The priority of this conditional formatting rule. This value is used to determine     which format should be evaluated and rendered. Lower numeric values are higher     priority than higher numeric values, where &#39;1&#39; is the highest priority. */
    public var priority: Int32?
    public var top10: Top10?
    public var _operator: String?
    public var iconSet: IconSet?
    /** Gets and sets whether the conditional format Type.              */
    public var type: String?
    public var timePeriod: String?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case aboveAverage = "AboveAverage"
        case formula2 = "Formula2"
        case style = "Style"
        case formula1 = "Formula1"
        case colorScale = "ColorScale"
        case dataBar = "DataBar"
        case text = "Text"
        case stopIfTrue = "StopIfTrue"
        case priority = "Priority"
        case top10 = "Top10"
        case _operator = "Operator"
        case iconSet = "IconSet"
        case type = "Type"
        case timePeriod = "TimePeriod"
    }

    public init(link: Link?, aboveAverage: AboveAverage?, formula2: String?, style: Style?, formula1: String?, colorScale: ColorScale?, dataBar: DataBar?, text: String?, stopIfTrue: Bool?, priority: Int32?, top10: Top10?, _operator: String?, iconSet: IconSet?, type: String?, timePeriod: String?) {
        self.link = link
        self.aboveAverage = aboveAverage
        self.formula2 = formula2
        self.style = style
        self.formula1 = formula1
        self.colorScale = colorScale
        self.dataBar = dataBar
        self.text = text
        self.stopIfTrue = stopIfTrue
        self.priority = priority
        self.top10 = top10
        self._operator = _operator
        self.iconSet = iconSet
        self.type = type
        self.timePeriod = timePeriod
    }


}

