//
// HorizontalPageBreakResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HorizontalPageBreakResponse: Codable {

    public var status: String?
    public var code: Int32
    public var horizontalPageBreak: HorizontalPageBreak?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case horizontalPageBreak = "HorizontalPageBreak"
    }

    public init(status: String?, code: Int32, horizontalPageBreak: HorizontalPageBreak?) {
        self.status = status
        self.code = code
        self.horizontalPageBreak = horizontalPageBreak
    }


}

