//
// HyperlinksResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class HyperlinksResponse: CellsCloudResponse {

    public var hyperlinks: Hyperlinks?

public enum CodingKeys: String, CodingKey {
        case hyperlinks = "Hyperlinks"
    }

    public init(status: String?, code: Int32, hyperlinks: Hyperlinks?) {
        self.hyperlinks = hyperlinks
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(hyperlinks, forKey: "Hyperlinks")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        hyperlinks = try container.decodeIfPresent(Hyperlinks.self, forKey: "Hyperlinks")
        try super.init(from: decoder)
    }

}

