//
// IconFilter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IconFilter: Codable {

    public var iconId: Int32
    public var iconSetType: String?

public enum CodingKeys: String, CodingKey { 
        case iconId = "IconId"
        case iconSetType = "IconSetType"
    }

    public init(iconId: Int32, iconSetType: String?) {
        self.iconId = iconId
        self.iconSetType = iconSetType
    }


}

