//
// ImportDataTaskParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImportDataTaskParameter: Codable {

    public var workbook: FileSource?
    public var importOption: ImportOption?
    public var destinationWorkbook: FileSource?

public enum CodingKeys: String, CodingKey { 
        case workbook = "Workbook"
        case importOption = "ImportOption"
        case destinationWorkbook = "DestinationWorkbook"
    }

    public init(workbook: FileSource?, importOption: ImportOption?, destinationWorkbook: FileSource?) {
        self.workbook = workbook
        self.importOption = importOption
        self.destinationWorkbook = destinationWorkbook
    }


}

