//
// ImportStringArrayOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImportStringArrayOption: Codable {

    public var source: FileSource?
    public var importDataType: String?
    public var destinationWorksheet: String?
    public var isInsert: Bool?
    public var data: [String]?
    public var isVertical: Bool?
    public var firstRow: Int32?
    public var firstColumn: Int32?

public enum CodingKeys: String, CodingKey { 
        case source = "Source"
        case importDataType = "ImportDataType"
        case destinationWorksheet = "DestinationWorksheet"
        case isInsert = "IsInsert"
        case data = "Data"
        case isVertical = "IsVertical"
        case firstRow = "FirstRow"
        case firstColumn = "FirstColumn"
    }

    public init(source: FileSource?, importDataType: String?, destinationWorksheet: String?, isInsert: Bool?, data: [String]?, isVertical: Bool?, firstRow: Int32?, firstColumn: Int32?) {
        self.source = source
        self.importDataType = importDataType
        self.destinationWorksheet = destinationWorksheet
        self.isInsert = isInsert
        self.data = data
        self.isVertical = isVertical
        self.firstRow = firstRow
        self.firstColumn = firstColumn
    }


}

