//
// LegendResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class LegendResponse: CellsCloudResponse {

    public var legend: Legend?

public enum CodingKeys: String, CodingKey {
        case legend = "Legend"
    }

    public init(status: String?, code: Int32, legend: Legend?) {
        self.legend = legend
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(legend, forKey: "Legend")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        legend = try container.decodeIfPresent(Legend.self, forKey: "Legend")
        try super.init(from: decoder)
    }

}

