//
// Line.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Line: Codable {

    public var style: String?
    public var isAuto: Bool?
    public var beginArrowLength: String?
    public var weight: String?
    public var gradientFill: GradientFill?
    public var color: Color?
    public var compoundType: String?
    public var weightPt: Double?
    public var isVisible: Bool?
    public var joinType: String?
    public var endArrowLength: String?
    public var isAutomaticColor: Bool?
    public var dashType: String?
    public var beginType: String?
    public var capType: String?
    public var endType: String?
    public var beginArrowWidth: String?
    public var endArrowWidth: String?
    public var transparency: Double?

public enum CodingKeys: String, CodingKey { 
        case style = "Style"
        case isAuto = "IsAuto"
        case beginArrowLength = "BeginArrowLength"
        case weight = "Weight"
        case gradientFill = "GradientFill"
        case color = "Color"
        case compoundType = "CompoundType"
        case weightPt = "WeightPt"
        case isVisible = "IsVisible"
        case joinType = "JoinType"
        case endArrowLength = "EndArrowLength"
        case isAutomaticColor = "IsAutomaticColor"
        case dashType = "DashType"
        case beginType = "BeginType"
        case capType = "CapType"
        case endType = "EndType"
        case beginArrowWidth = "BeginArrowWidth"
        case endArrowWidth = "EndArrowWidth"
        case transparency = "Transparency"
    }

    public init(style: String?, isAuto: Bool?, beginArrowLength: String?, weight: String?, gradientFill: GradientFill?, color: Color?, compoundType: String?, weightPt: Double?, isVisible: Bool?, joinType: String?, endArrowLength: String?, isAutomaticColor: Bool?, dashType: String?, beginType: String?, capType: String?, endType: String?, beginArrowWidth: String?, endArrowWidth: String?, transparency: Double?) {
        self.style = style
        self.isAuto = isAuto
        self.beginArrowLength = beginArrowLength
        self.weight = weight
        self.gradientFill = gradientFill
        self.color = color
        self.compoundType = compoundType
        self.weightPt = weightPt
        self.isVisible = isVisible
        self.joinType = joinType
        self.endArrowLength = endArrowLength
        self.isAutomaticColor = isAutomaticColor
        self.dashType = dashType
        self.beginType = beginType
        self.capType = capType
        self.endType = endType
        self.beginArrowWidth = beginArrowWidth
        self.endArrowWidth = endArrowWidth
        self.transparency = transparency
    }


}

