//
// Link.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Link: Codable {

    public var href: String?
    public var type: String?
    public var rel: String?
    public var title: String?

public enum CodingKeys: String, CodingKey { 
        case href = "Href"
        case type = "Type"
        case rel = "Rel"
        case title = "Title"
    }

    public init(href: String?, type: String?, rel: String?, title: String?) {
        self.href = href
        self.type = type
        self.rel = rel
        self.title = title
    }


}

