//
// LinkElement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LinkElement: Codable {

    public var link: Link?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
    }

    public init(link: Link?) {
        self.link = link
    }


}

