//
// ListObjectsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListObjectsResponse: Codable {

    public var status: String?
    public var code: Int32
    public var listObjects: ListObjects?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case listObjects = "ListObjects"
    }

    public init(status: String?, code: Int32, listObjects: ListObjects?) {
        self.status = status
        self.code = code
        self.listObjects = listObjects
    }


}

