//
// MergedCells.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MergedCells: Codable {

    public var link: Link?
    public var count: Int32
    public var mergedCellList: [LinkElement]?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case count = "Count"
        case mergedCellList = "MergedCellList"
    }

    public init(link: Link?, count: Int32, mergedCellList: [LinkElement]?) {
        self.link = link
        self.count = count
        self.mergedCellList = mergedCellList
    }


}

