//
// NamesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class NamesResponse: CellsCloudResponse {

    public var names: Names?

public enum CodingKeys: String, CodingKey {
        case names = "Names"
    }

    public init(status: String?, code: Int32, names: Names?) {
        self.names = names
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(names, forKey: "Names")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        names = try container.decodeIfPresent(Names.self, forKey: "Names")
        try super.init(from: decoder)
    }

}

