//
// OperateParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OperateParameter: Codable {

    public var operateType: String?

public enum CodingKeys: String, CodingKey { 
        case operateType = "OperateType"
    }

    public init(operateType: String?) {
        self.operateType = operateType
    }


}

