//
// OperateParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class OperateParameter: Codable {

    public var operateType: String?

public enum CodingKeys: String, CodingKey { 
        case operateType = "OperateType"
    }

    public init(operateType: String?) {
        self.operateType = operateType
    }

    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(operateType, forKey: "OperateType")
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        operateType = try container.decodeIfPresent(String.self, forKey: "OperateType")
    }

}

