//
// PageSetupOperateParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageSetupOperateParameter: Codable {

    public var operateType: String?
    public var pageSetup: PageSetup?

public enum CodingKeys: String, CodingKey { 
        case operateType = "OperateType"
        case pageSetup = "PageSetup"
    }

    public init(operateType: String?, pageSetup: PageSetup?) {
        self.operateType = operateType
        self.pageSetup = pageSetup
    }


}

