//
// PageSectionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageSectionsResponse: Codable {

    public var status: String?
    public var code: Int32
    public var pageSections: [PageSection]?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case pageSections = "PageSections"
    }

    public init(status: String?, code: Int32, pageSections: [PageSection]?) {
        self.status = status
        self.code = code
        self.pageSections = pageSections
    }


}

