//
// PageSetupResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageSetupResponse: Codable {

    public var status: String?
    public var code: Int32
    public var pageSetup: PageSetup?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case pageSetup = "PageSetup"
    }

    public init(status: String?, code: Int32, pageSetup: PageSetup?) {
        self.status = status
        self.code = code
        self.pageSetup = pageSetup
    }


}

