//
// PasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used for password data transfer. */

public struct PasswordRequest: Codable {

    public var password: String?

public enum CodingKeys: String, CodingKey { 
        case password = "Password"
    }

    public init(password: String?) {
        self.password = password
    }


}

