//
// PictureResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class PictureResponse: CellsCloudResponse {

    public var picture: Picture?

public enum CodingKeys: String, CodingKey {
        case picture = "Picture"
    }

    public init(status: String?, code: Int32, picture: Picture?) {
        self.picture = picture
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(picture, forKey: "Picture")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        picture = try container.decodeIfPresent(Picture.self, forKey: "Picture")
        try super.init(from: decoder)
    }

}

