//
// PicturesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PicturesResponse: Codable {

    public var status: String?
    public var code: Int32
    public var pictures: Pictures?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case pictures = "Pictures"
    }

    public init(status: String?, code: Int32, pictures: Pictures?) {
        self.status = status
        self.code = code
        self.pictures = pictures
    }


}

