//
// PivotTableOperateParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PivotTableOperateParameter: Codable {

    public var operateType: String?
    public var pivotFieldColumns: [Int32]?
    public var pivotTableIndex: Int32?
    public var tableName: String?
    public var useSameSource: Bool?
    public var pivotFieldData: [Int32]?
    public var pivotFieldRows: [Int32]?
    public var destCellName: String?
    public var sourceData: String?

public enum CodingKeys: String, CodingKey { 
        case operateType = "OperateType"
        case pivotFieldColumns = "PivotFieldColumns"
        case pivotTableIndex = "PivotTableIndex"
        case tableName = "TableName"
        case useSameSource = "UseSameSource"
        case pivotFieldData = "PivotFieldData"
        case pivotFieldRows = "PivotFieldRows"
        case destCellName = "DestCellName"
        case sourceData = "SourceData"
    }

    public init(operateType: String?, pivotFieldColumns: [Int32]?, pivotTableIndex: Int32?, tableName: String?, useSameSource: Bool?, pivotFieldData: [Int32]?, pivotFieldRows: [Int32]?, destCellName: String?, sourceData: String?) {
        self.operateType = operateType
        self.pivotFieldColumns = pivotFieldColumns
        self.pivotTableIndex = pivotTableIndex
        self.tableName = tableName
        self.useSameSource = useSameSource
        self.pivotFieldData = pivotFieldData
        self.pivotFieldRows = pivotFieldRows
        self.destCellName = destCellName
        self.sourceData = sourceData
    }


}

