//
// PivotTables.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PivotTables: Codable {

    public var link: Link?
    public var pivotTableList: [LinkElement]?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case pivotTableList = "PivotTableList"
    }

    public init(link: Link?, pivotTableList: [LinkElement]?) {
        self.link = link
        self.pivotTableList = pivotTableList
    }


}

