//
// PivotTableFieldRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PivotTableFieldRequest: Codable {

    public var data: [Int32]?

public enum CodingKeys: String, CodingKey { 
        case data = "Data"
    }

    public init(data: [Int32]?) {
        self.data = data
    }


}

