//
// Ranges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Ranges: Codable {

    public var rangeList: [Range]?

public enum CodingKeys: String, CodingKey { 
        case rangeList = "RangeList"
    }

    public init(rangeList: [Range]?) {
        self.rangeList = rangeList
    }


}

