//
// RangesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RangesResponse: Codable {

    public var status: String?
    public var code: Int32
    public var ranges: Ranges?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case ranges = "Ranges"
    }

    public init(status: String?, code: Int32, ranges: Ranges?) {
        self.status = status
        self.code = code
        self.ranges = ranges
    }


}

