//
// RowsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class RowsResponse: CellsCloudResponse {

    public var rows: Rows?

public enum CodingKeys: String, CodingKey {
        case rows = "Rows"
    }

    public init(status: String?, code: Int32, rows: Rows?) {
        self.rows = rows
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(rows, forKey: "Rows")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        rows = try container.decodeIfPresent(Rows.self, forKey: "Rows")
        try super.init(from: decoder)
    }

}

