//
// SaveResultTaskParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SaveResultTaskParameter: Codable {

    public var resultSource: String?
    public var resultDestination: ResultDestination?

public enum CodingKeys: String, CodingKey { 
        case resultSource = "ResultSource"
        case resultDestination = "ResultDestination"
    }

    public init(resultSource: String?, resultDestination: ResultDestination?) {
        self.resultSource = resultSource
        self.resultDestination = resultDestination
    }


}

