//
// ShadowEffect.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShadowEffect: Codable {

    public var distance: Double?
    public var angle: Double?
    public var presetType: String?
    public var color: CellsColor?
    public var transparency: Double?
    public var blur: Double?
    public var size: Double?

public enum CodingKeys: String, CodingKey { 
        case distance = "Distance"
        case angle = "Angle"
        case presetType = "PresetType"
        case color = "Color"
        case transparency = "Transparency"
        case blur = "Blur"
        case size = "Size"
    }

    public init(distance: Double?, angle: Double?, presetType: String?, color: CellsColor?, transparency: Double?, blur: Double?, size: Double?) {
        self.distance = distance
        self.angle = angle
        self.presetType = presetType
        self.color = color
        self.transparency = transparency
        self.blur = blur
        self.size = size
    }


}

