//
// ShapesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ShapesResponse: CellsCloudResponse {

    public var shapes: Shapes?

public enum CodingKeys: String, CodingKey {
        case shapes = "Shapes"
    }

    public init(status: String?, code: Int32, shapes: Shapes?) {
        self.shapes = shapes
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(shapes, forKey: "Shapes")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        shapes = try container.decodeIfPresent(Shapes.self, forKey: "Shapes")
        try super.init(from: decoder)
    }

}

