//
// SingleValueResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SingleValueResponse: CellsCloudResponse {

    public var value: SingleValue?

public enum CodingKeys: String, CodingKey {
        case value = "Value"
    }

    public init(status: String?, code: Int32, value: SingleValue?) {
        self.value = value
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(value, forKey: "Value")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        value = try container.decodeIfPresent(SingleValue.self, forKey: "Value")
        try super.init(from: decoder)
    }

}

