//
// SingleValueResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SingleValueResponse: Codable {

    public var status: String?
    public var code: Int32
    public var value: SingleValue?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case value = "Value"
    }

    public init(status: String?, code: Int32, value: SingleValue?) {
        self.status = status
        self.code = code
        self.value = value
    }


}

