//
// SplitResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SplitResult: Codable {

    public var documents: [SplitResultDocument]?

public enum CodingKeys: String, CodingKey { 
        case documents = "Documents"
    }

    public init(documents: [SplitResultDocument]?) {
        self.documents = documents
    }


}

