//
// SplitWorkbookTaskParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SplitWorkbookTaskParameter: Codable {

    public var destinationFileFormat: String?
    public var destinationFilePosition: FileSource?
    public var verticalResolution: Int32?
    public var horizontalResolution: Int32?
    public var splitNameRule: String?
    public var workbook: FileSource?

public enum CodingKeys: String, CodingKey { 
        case destinationFileFormat = "DestinationFileFormat"
        case destinationFilePosition = "DestinationFilePosition"
        case verticalResolution = "VerticalResolution"
        case horizontalResolution = "HorizontalResolution"
        case splitNameRule = "SplitNameRule"
        case workbook = "Workbook"
    }

    public init(destinationFileFormat: String?, destinationFilePosition: FileSource?, verticalResolution: Int32?, horizontalResolution: Int32?, splitNameRule: String?, workbook: FileSource?) {
        self.destinationFileFormat = destinationFileFormat
        self.destinationFilePosition = destinationFilePosition
        self.verticalResolution = verticalResolution
        self.horizontalResolution = horizontalResolution
        self.splitNameRule = splitNameRule
        self.workbook = workbook
    }


}

