//
// SplitResultResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SplitResultResponse: CellsCloudResponse {

    /** Gets or sets the splitting result. */
    public var result: SplitResult?

public enum CodingKeys: String, CodingKey {
        case result = "Result"
    }

    public init(status: String?, code: Int32, result: SplitResult?) {
        self.result = result
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(result, forKey: "Result")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        result = try container.decodeIfPresent(SplitResult.self, forKey: "Result")
        try super.init(from: decoder)
    }

}

