//
// SplitResultResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SplitResultResponse: Codable {

    public var status: String?
    public var code: Int32
    /** Gets or sets the splitting result. */
    public var result: SplitResult?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case result = "Result"
    }

    public init(status: String?, code: Int32, result: SplitResult?) {
        self.status = status
        self.code = code
        self.result = result
    }


}

