//
// StorageExist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Storage exists */

public struct StorageExist: Codable {

    /** Shows that the storage exists.              */
    public var exists: Bool

public enum CodingKeys: String, CodingKey { 
        case exists = "Exists"
    }

    public init(exists: Bool) {
        self.exists = exists
    }


}

