//
// TaskDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaskDescription: Codable {

    public var taskParameter: TaskParameter?
    public var taskType: String?

public enum CodingKeys: String, CodingKey { 
        case taskParameter = "TaskParameter"
        case taskType = "TaskType"
    }

    public init(taskParameter: TaskParameter?, taskType: String?) {
        self.taskParameter = taskParameter
        self.taskType = taskType
    }


}

