//
// TextureFill.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TextureFill: Codable {

    public var scale: Double?
    public var image: LinkElement?
    public var picFormatOption: PicFormatOption?
    public var tilePicOption: TilePicOption?
    public var transparency: Double?
    public var type: String?

public enum CodingKeys: String, CodingKey { 
        case scale = "Scale"
        case image = "Image"
        case picFormatOption = "PicFormatOption"
        case tilePicOption = "TilePicOption"
        case transparency = "Transparency"
        case type = "Type"
    }

    public init(scale: Double?, image: LinkElement?, picFormatOption: PicFormatOption?, tilePicOption: TilePicOption?, transparency: Double?, type: String?) {
        self.scale = scale
        self.image = image
        self.picFormatOption = picFormatOption
        self.tilePicOption = tilePicOption
        self.transparency = transparency
        self.type = type
    }


}

