//
// ThemeColor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ThemeColor: Codable {

    public var tint: Double?
    public var colorType: String?

public enum CodingKeys: String, CodingKey { 
        case tint = "Tint"
        case colorType = "ColorType"
    }

    public init(tint: Double?, colorType: String?) {
        self.tint = tint
        self.colorType = colorType
    }


}

