//
// TilePicOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TilePicOption: Codable {

    public var alignmentType: String?
    public var offsetX: Double
    public var scaleX: Double
    public var offsetY: Double
    public var scaleY: Double
    public var mirrorType: String?

public enum CodingKeys: String, CodingKey { 
        case alignmentType = "AlignmentType"
        case offsetX = "OffsetX"
        case scaleX = "ScaleX"
        case offsetY = "OffsetY"
        case scaleY = "ScaleY"
        case mirrorType = "MirrorType"
    }

    public init(alignmentType: String?, offsetX: Double, scaleX: Double, offsetY: Double, scaleY: Double, mirrorType: String?) {
        self.alignmentType = alignmentType
        self.offsetX = offsetX
        self.scaleX = scaleX
        self.offsetY = offsetY
        self.scaleY = scaleY
        self.mirrorType = mirrorType
    }


}

