//
// TitleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TitleResponse: Codable {

    public var status: String?
    public var code: Int32
    public var title: Title?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case title = "Title"
    }

    public init(status: String?, code: Int32, title: Title?) {
        self.status = status
        self.code = code
        self.title = title
    }


}

