//
// Top10.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describe the Top10 conditional formatting rule. This conditional formatting     rule highlights cells whose values fall in the top N or bottom N bracket,     as specified. */

public struct Top10: Codable {

    /** Get or set the flag indicating whether a \&quot;top/bottom n\&quot; rule is a \&quot;bottom    n\&quot; rule. &#39;1&#39; indicates &#39;bottom&#39;.  Default value is false.              */
    public var isBottom: Bool?
    /** Get or set the flag indicating whether a \&quot;top/bottom n\&quot; rule is a \&quot;top/bottom     n percent\&quot; rule.  Default value is false. */
    public var isPercent: Bool?
    /** Get or set the value of \&quot;n\&quot; in a \&quot;top/bottom n\&quot; conditional formatting rule.      If IsPercent is true, the value must between 0 and 100.  Otherwise it must     between 0 and 1000.  Default value is 10. */
    public var rank: Int32?

public enum CodingKeys: String, CodingKey { 
        case isBottom = "IsBottom"
        case isPercent = "IsPercent"
        case rank = "Rank"
    }

    public init(isBottom: Bool?, isPercent: Bool?, rank: Int32?) {
        self.isBottom = isBottom
        self.isPercent = isPercent
        self.rank = rank
    }


}

