//
// Top10Filter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Top10Filter: Codable {

    public var items: Int32
    public var isPercent: Bool
    public var isTop: Bool
    public var criteria: String?

public enum CodingKeys: String, CodingKey { 
        case items = "Items"
        case isPercent = "IsPercent"
        case isTop = "IsTop"
        case criteria = "Criteria"
    }

    public init(items: Int32, isPercent: Bool, isTop: Bool, criteria: String?) {
        self.items = items
        self.isPercent = isPercent
        self.isTop = isTop
        self.criteria = criteria
    }


}

