//
// ValidationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ValidationResponse: Codable {

    public var status: String?
    public var code: Int32
    public var validation: Validation?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case validation = "Validation"
    }

    public init(status: String?, code: Int32, validation: Validation?) {
        self.status = status
        self.code = code
        self.validation = validation
    }


}

