//
// VerticalPageBreakResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VerticalPageBreakResponse: Codable {

    public var status: String?
    public var code: Int32
    public var verticalPageBreak: VerticalPageBreak?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case verticalPageBreak = "VerticalPageBreak"
    }

    public init(status: String?, code: Int32, verticalPageBreak: VerticalPageBreak?) {
        self.status = status
        self.code = code
        self.verticalPageBreak = verticalPageBreak
    }


}

