//
// VerticalPageBreaks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VerticalPageBreaks: Codable {

    public var link: Link?
    public var verticalPageBreakList: [VerticalPageBreak]?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case verticalPageBreakList = "VerticalPageBreakList"
    }

    public init(link: Link?, verticalPageBreakList: [VerticalPageBreak]?) {
        self.link = link
        self.verticalPageBreakList = verticalPageBreakList
    }


}

