//
// VerticalPageBreak.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VerticalPageBreak: Codable {

    public var column: Int32
    public var startRow: Int32
    public var endRow: Int32

public enum CodingKeys: String, CodingKey { 
        case column = "Column"
        case startRow = "StartRow"
        case endRow = "EndRow"
    }

    public init(column: Int32, startRow: Int32, endRow: Int32) {
        self.column = column
        self.startRow = startRow
        self.endRow = endRow
    }


}

