//
// VerticalPageBreakResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class VerticalPageBreakResponse: CellsCloudResponse {

    public var verticalPageBreak: VerticalPageBreak?

public enum CodingKeys: String, CodingKey {
        case verticalPageBreak = "VerticalPageBreak"
    }

    public init(status: String?, code: Int32, verticalPageBreak: VerticalPageBreak?) {
        self.verticalPageBreak = verticalPageBreak
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(verticalPageBreak, forKey: "VerticalPageBreak")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        verticalPageBreak = try container.decodeIfPresent(VerticalPageBreak.self, forKey: "VerticalPageBreak")
        try super.init(from: decoder)
    }

}

