//
// WorkbookSettingsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkbookSettingsResponse: Codable {

    public var status: String?
    public var code: Int32
    public var settings: WorkbookSettings?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case settings = "settings"
    }

    public init(status: String?, code: Int32, settings: WorkbookSettings?) {
        self.status = status
        self.code = code
        self.settings = settings
    }


}

