//
// Worksheets.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Worksheets: Codable {

    public var link: Link?
    public var worksheetList: [LinkElement]?

public enum CodingKeys: String, CodingKey { 
        case link = "link"
        case worksheetList = "WorksheetList"
    }

    public init(link: Link?, worksheetList: [LinkElement]?) {
        self.link = link
        self.worksheetList = worksheetList
    }


}

