//
// WorksheetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class WorksheetResponse: CellsCloudResponse {

    public var worksheet: Worksheet?

public enum CodingKeys: String, CodingKey {
        case worksheet = "Worksheet"
    }

    public init(status: String?, code: Int32, worksheet: Worksheet?) {
        self.worksheet = worksheet
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(worksheet, forKey: "Worksheet")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        worksheet = try container.decodeIfPresent(Worksheet.self, forKey: "Worksheet")
        try super.init(from: decoder)
    }

}

