//
// WorkbookSettingsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class WorkbookSettingsResponse: CellsCloudResponse {

    public var settings: WorkbookSettings?

public enum CodingKeys: String, CodingKey {
        case settings = "settings"
    }

    public init(status: String?, code: Int32, settings: WorkbookSettings?) {
        self.settings = settings
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(settings, forKey: "settings")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        settings = try container.decodeIfPresent(WorkbookSettings.self, forKey: "settings")
        try super.init(from: decoder)
    }

}

