//
// WorksheetsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class WorksheetsResponse: CellsCloudResponse {

    public var worksheets: Worksheets?

public enum CodingKeys: String, CodingKey {
        case worksheets = "Worksheets"
    }

    public init(status: String?, code: Int32, worksheets: Worksheets?) {
        self.worksheets = worksheets
        super.init(status: status, code: code)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(worksheets, forKey: "Worksheets")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        worksheets = try container.decodeIfPresent(Worksheets.self, forKey: "Worksheets")
        try super.init(from: decoder)
    }

}

