//
// WorksheetMovingRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used by workbook moving requests. */

public struct WorksheetMovingRequest: Codable {

    /** Position to move. Can be BEFORE or AFTER. */
    public var position: String?
    /** Destination worksheet name.   */
    public var destinationWorksheet: String?

public enum CodingKeys: String, CodingKey { 
        case position = "Position"
        case destinationWorksheet = "DestinationWorksheet"
    }

    public init(position: String?, destinationWorksheet: String?) {
        self.position = position
        self.destinationWorksheet = destinationWorksheet
    }


}

