//
// WorkbookResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkbookResponse: Codable {

    public var status: String?
    public var code: Int32
    public var workbook: Workbook?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case workbook = "Workbook"
    }

    public init(status: String?, code: Int32, workbook: Workbook?) {
        self.status = status
        self.code = code
        self.workbook = workbook
    }


}

