//
// CellsTaskAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CellsTaskAPI {
    /**
     Run tasks  
     
     - parameter taskData: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func cellsTaskPostRunTask(taskData: TaskData, completion: @escaping ((_ data: AnyObject?,_ error: Error?) -> Void)) {
        cellsTaskPostRunTaskWithRequestBuilder(taskData: taskData).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Run tasks  
     - POST /cells/task/runtask
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter taskData: (body)  

     - returns: RequestBuilder<AnyObject> 
     */
    open class func cellsTaskPostRunTaskWithRequestBuilder(taskData: TaskData) -> RequestBuilder<AnyObject> {
        let path = "/cells/task/runtask"
        let URLString = AsposeCellsCloudAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: taskData)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<AnyObject>.Type = AsposeCellsCloudAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
